version: '3.7'

services:
  backend:
    build: .
    ports:
      - 80:5000
      - 443:5000
    volumes:
      - .:/app
    depends_on:
      - redis
      - worker
    restart: always

  worker:
    build:
      context: ./celery_worker
      dockerfile: Dockerfile
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./celery_worker:/queue']

  monitor:
    build:
      context: ./celery_worker
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    command: celery -A tasks flower
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - worker
    volumes: ['./celery_worker:/queue']

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
